first_number=input("Enter a number:")
second_number=input("Enter a number:")
sum=int(first_number)+int(second_number)
subtraction=int(first_number)-int(second_number)
multiplication=int(first_number)*int(second_number)
division=int(first_number)/int(second_number)
print("sum: ",sum)
print("subtraction: ",subtraction)
print("multiplication: ",multiplication)
print("division: ",division)